#!/bin/bash
#
# Imports the ridership JSON file into a DuckDB table called "ridership". This
# is useful for running OLAP queries against the ridership dataset.
#
# Requires duckdb and jq.

DB_FILE="ridership.duckdb"

read -rd '' CREATE_QUERY << EOF
CREATE TABLE
    ridership
AS SELECT
    entries.key::DATE as date,
    entries.value.riders,
    entries.value.percent_baseline
FROM (
    SELECT
        unnest(map_entries(json)) as entries
    FROM 
        read_json('$(git rev-parse --show-toplevel)/ridership.json')
);
EOF

if [[ -f "$DB_FILE" ]]; then
    duckdb -c "DROP TABLE IF EXISTS ridership" "$DB_FILE"
fi

duckdb -c "$CREATE_QUERY" "$DB_FILE"
