#!/bin/bash
#
# Imports the ridership JSON file into a DuckDB table called "ridership". This
# is useful for running OLAP queries against the ridership dataset.
#
# Requires duckdb and jq.

DB_FILE="ridership.duckdb"

read -rd '' CREATE_QUERY << EOF
CREATE TABLE ridership
AS SELECT * FROM
read_csv(
    '/dev/stdin', 
    header=False, 
    columns={'date': 'DATE', 'riders': 'UINTEGER', 'percent_baseline': 'UTINYINT'}, 
    dateformat='%-m/%-d/%-y'
)
EOF

if [[ -f "$DB_FILE" ]]; then
    duckdb -c "DROP TABLE IF EXISTS ridership" "$DB_FILE"
fi

jq -r \
    'to_entries[] | [.key, .value.riders, .value.percent_baseline] | @csv' ridership.json \
    | duckdb -c "$CREATE_QUERY" "$DB_FILE"
