name: Data Archive

on:
  push:
  schedule:
    - cron: '0 5 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        id: pyinstall
        with:
          python-version: '3.11' 
      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4
      - name: Run collector
        run: |
          python -m collector
      - name: Commit data
        run: |
          git config user.name "Archive"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          git commit -m "Archive from $(date -u)" || exit 0
          git push