name: Data Archive

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 5 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install moreutils
        run: |
          sudo apt update
          sudo apt install -y --no-install-recommends --no-install-suggests moreutils
      - uses: MrFlynn/flyscrape-action@v1
        id: scrape
        with:
          script: 'scripts/ridership.js'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Update ridership.json
        run: |
          jq -cs \
            '(.[0] * (.[1] | first | .data)) | to_entries | sort_by(.key |= (strptime("%m/%d/%y") | mktime)) | from_entries' \
            ridership.json <(echo '${{ steps.scrape.outputs.output }}') | sponge ridership.json
      - name: Commit data
        run: |
          git config user.name "Archive"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          git commit -m "Archive from $(date -u)" || exit 0
          git push
  update-badge:
    runs-on: ubuntu-latest
    needs: scheduled
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main
      - name: Extract latest ridership value and set environment variables
        run: |
          jq -r \
            'to_entries | sort_by(.key |= (strptime("%m/%d/%y") | mktime)) | last | @sh "DATE=\(.key)\nRIDERS=\(.value.riders)"' \
            ridership.json | tr -d "'" >> $GITHUB_ENV
      - uses: schneegans/dynamic-badges-action@v1.7.0
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          gistID: e734700d586151d29d8da4b56639d8d7
          filename: riders.json
          label: ${{ env.DATE }}
          message: ${{ env.RIDERS }}
          color: blue
