name: Data Archive

on:
  push:
  schedule:
    - cron: '0 5 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install pipenv
        run: |
          pip install --user pipenv
      - name: Run collector
        run: |
          pipenv install
          pipenv run collec
      - name: Commit data
        run: |
          git config user.name "Archive"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          git commit -m "Archive from $(date -u)" || exit 0
          git push